# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:02:25 2018 from module list in Acme::CPANLists::Import::PerlDancerAdvent::2016_12_02 version 0.001.

package Acme::CPANModules::Import::PerlDancerAdvent::2016_12_02;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/2] (retrieved on 2017-01-31). Visit the URL for the full contents.",
  entries     => [
                   { module => "DBIx::Class" },
                   { module => "Dancer2" },
                   { module => "Dancer2::Debugger" },
                   { module => "Dancer2::Plugin" },
                   { module => "Dancer2::Plugin::Auth::ActiveDirectory" },
                   { module => "Dancer2::Plugin::Auth::Extensible" },
                   { module => "Dancer2::Plugin::Auth::Extensible::Provider::IMAP" },
                   { module => "Dancer2::Plugin::Auth::Extensible::Provider::LDAP" },
                   { module => "Dancer2::Plugin::Auth::SAFE" },
                   { module => "Dancer2::Plugin::BeforeRoute" },
                   { module => "Dancer2::Plugin::Cart" },
                   { module => "Dancer2::Plugin::DBIC" },
                   { module => "Dancer2::Plugin::Database" },
                   { module => "Dancer2::Plugin::EncryptID" },
                   { module => "Dancer2::Plugin::HTTP::Auth::Extensible" },
                   { module => "Dancer2::Plugin::Interchange6" },
                   { module => "Dancer2::Plugin::Minify" },
                   { module => "Dancer2::Plugin::PageHistory" },
                   { module => "Dancer2::Plugin::Pg" },
                   { module => "Dancer2::Plugin::Swagger2" },
                   { module => "Dancer2::Plugin::Tail" },
                   { module => "Dancer2::Plugin::TemplateFlute" },
                   { module => "Dancer2::Template::TemplateFlute" },
                   { module => "Interchange6" },
                   { module => "Interchange6::Schema" },
                   { module => "Moo" },
                   { module => "Plack::Debugger" },
                   { module => "Plack::Middleware::Debug" },
                   { module => "Template::Flute" },
                 ],
  summary     => "Modules mentioned in PerlDancer Advent Calendar 2016 (day 2)",
};

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 2)

