# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:02:27 2018 from module list in Acme::CPANLists::Import::PerlDancerAdvent::2016_12_21 version 0.001.

package Acme::CPANModules::Import::PerlDancerAdvent::2016_12_21;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/21] (retrieved on 2017-01-31). Visit the URL for the full contents.",
  entries     => [
                   { module => "Dancer2::Core::App" },
                   { module => "Exporter" },
                   { module => "List::Util" },
                 ],
  summary     => "Modules mentioned in PerlDancer Advent Calendar 2016 (day 21)",
};

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 21)

