# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:02:26 2018 from module list in Acme::CPANLists::Import::PerlDancerAdvent::2016_12_12 version 0.001.

package Acme::CPANModules::Import::PerlDancerAdvent::2016_12_12;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/12] (retrieved on 2017-01-31). Visit the URL for the full contents.",
  entries     => [
                   { module => "AnyEvent" },
                   { module => "App::FatPacker" },
                   { module => "CGI" },
                   { module => "CGI::Deurl::XS" },
                   { module => "Class::XSAccessor" },
                   { module => "Config::Any" },
                   { module => "Cpanel::JSON::XS" },
                   { module => "Crypt::URandom" },
                   { module => "EV" },
                   { module => "HTTP::Parser::XS" },
                   { module => "HTTP::XSCookies" },
                   { module => "JSON" },
                   { module => "JSON::MaybeXS" },
                   { module => "JSON::XS" },
                   { module => "Math::Random::ISAAC::XS" },
                   { module => "Moo" },
                   { module => "Plack" },
                   { module => "Return::MultiLevel" },
                   { module => "Scope::Upper" },
                   { module => "URL::Encode" },
                   { module => "URL::Encode::XS" },
                   { module => "YAML::XS" },
                 ],
  summary     => "Modules mentioned in PerlDancer Advent Calendar 2016 (day 12)",
};

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 12)

