# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:02:26 2018 from module list in Acme::CPANLists::Import::PerlDancerAdvent::2016_12_10 version 0.001.

package Acme::CPANModules::Import::PerlDancerAdvent::2016_12_10;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/10] (retrieved on 2017-01-31). Visit the URL for the full contents.",
  entries     => [
                   { module => "Dancer2::Logger::LogReport" },
                   { module => "Dancer2::Plugin::LogReport" },
                   { module => "Log::Report" },
                   { module => "Log::Report::DBIC::Profiler" },
                   { module => "Log::Report::Dispatcher::Syslog" },
                   { module => "Log::Report::Translator" },
                 ],
  summary     => "Modules mentioned in PerlDancer Advent Calendar 2016 (day 10)",
};

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 10)

