# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 08:02:26 2018 from module list in Acme::CPANLists::Import::PerlDancerAdvent::2016_12_11 version 0.001.

package Acme::CPANModules::Import::PerlDancerAdvent::2016_12_11;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/11] (retrieved on 2017-01-31). Visit the URL for the full contents.",
  entries     => [
                   { module => "Dancer2::Plugin::LogReport" },
                   { module => "Locale::TextDomain" },
                   { module => "Log::Report" },
                   { module => "Log::Report::Extract::PerlPPI" },
                   { module => "Log::Report::Extract::Template" },
                 ],
  summary     => "Modules mentioned in PerlDancer Advent Calendar 2016 (day 11)",
};

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 11)

