package Acme::CPANModules::Import::PerlDancerAdvent::2018;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2018] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Plugin::WebSocket"},{module=>"Dancer2::Plugin::Captcha"},{module=>"Dancer2::Plugin::Chain"},{module=>"Dancer2::Plugin::Paginator"},{module=>"Dancer2::Plugin::Res"},{module=>"Paginator::Lite"},{module=>"Minion"},{module=>"Dancer2::Plugin::Email"},{module=>"Email::Sender"},{module=>"Email::Sender::Transport::Redirect"},{module=>"HTML::FormatText::WithLinks"},{module=>"App::Cmd"},{module=>"Dancer2"},{module=>"Dancer2::Logger::Log4perl"},{module=>"Log::Log4perl"},{module=>"Log::Log4perl::Appender::File"},{module=>"Log::Log4perl::Layout::PatternLayout"},{module=>"Dancer2::Template::Simple"},{module=>"Mojolicious::Plugin::MountPSGI"},{module=>"PSGI"},{module=>"Plack::Test"},{module=>"Test::Mojo::Role::PSGI"},{module=>"Dancer2::Plugin::ParamTypes"},{module=>"Dancer2::Core::Role::Logger"},{module=>"Dancer2::Logger::Console::Colored"},{module=>"Mojo::Log::Colored"},{module=>"Term::ANSIColor"}],summary=>"Modules mentioned in Perl Dancer Advent Calendar 2018"};

1;
# ABSTRACT: Modules mentioned in Perl Dancer Advent Calendar 2018

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2018> (retrieved on 2018-12-30). Visit the URL for the full contents.

