package Acme::CPANModules::Import::PerlDancerAdvent::2018_12_19;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2018/19] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Logger::Log4perl"},{module=>"Log::Log4perl"},{module=>"Log::Log4perl::Appender::File"},{module=>"Log::Log4perl::Layout::PatternLayout"}],summary=>"Modules mentioned in Perl Dancer Advent Calendar 2018 (day 19)"};

1;
# ABSTRACT: Modules mentioned in Perl Dancer Advent Calendar 2018 (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2018/19> (retrieved on 2018-12-30). Visit the URL for the full contents.

