package Acme::CPANModules::Import::PerlDancerAdvent::2018_12_23;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2018/23] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Core::Role::Logger"},{module=>"Dancer2::Logger::Console::Colored"},{module=>"Mojo::Log::Colored"},{module=>"Term::ANSIColor"}],summary=>"Modules mentioned in Perl Dancer Advent Calendar 2018 (day 23)"};

1;
# ABSTRACT: Modules mentioned in Perl Dancer Advent Calendar 2018 (day 23)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2018/23> (retrieved on 2018-12-30). Visit the URL for the full contents.

