package Acme::CPANModules::Import::PerlDancerAdvent::2018_12_15;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2018/15] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Plugin::Captcha"},{module=>"Dancer2::Plugin::Chain"},{module=>"Dancer2::Plugin::Paginator"},{module=>"Dancer2::Plugin::Res"},{module=>"Paginator::Lite"}],summary=>"Modules mentioned in Perl Dancer Advent Calendar 2018 (day 15)"};

1;
# ABSTRACT: Modules mentioned in Perl Dancer Advent Calendar 2018 (day 15)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2018/15> (retrieved on 2018-12-30). Visit the URL for the full contents.

