package Acme::CPANModules::Import::PerlDancerAdvent::2018_12_13;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2018/13] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Plugin::WebSocket"}],summary=>"Modules mentioned in Perl Dancer Advent Calendar 2018 (day 13)"};

1;
# ABSTRACT: Modules mentioned in Perl Dancer Advent Calendar 2018 (day 13)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2018/13> (retrieved on 2018-12-30). Visit the URL for the full contents.

