package Acme::CPANModules::Import::PerlDancerAdvent::2018_12_18;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2018/18] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"App::Cmd"},{module=>"Dancer2"}],summary=>"Modules mentioned in Perl Dancer Advent Calendar 2018 (day 18)"};

1;
# ABSTRACT: Modules mentioned in Perl Dancer Advent Calendar 2018 (day 18)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2018/18> (retrieved on 2018-12-30). Visit the URL for the full contents.

